### ISSUE TITLE
[Issue]: Crash on 1.3.8 calling for client classes on server

### ISSUE THREAD

**Issue by Milii20** [Louis-LD29/OmoshiroiKamo#61]
### Description

Hello!, i do think server is trying to load something from client, specially because of the "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class ruiseki.omoshiroikamo.api.client.JsonModelISBRH", was working perfectly on 1.3.6.
Thank you for your time and amazing mod!

### fml_client_latest.log, and crash reports, if any.

[crash-2025-11-27_15.27.32-server.txt](https://github.com/user-attachments/files/23809920/crash-2025-11-27_15.27.32-server.txt)

[fml-server-latest.log](https://github.com/user-attachments/files/23809922/fml-server-latest.log)

### I have submitted the required files

- [x] I confirm that i have attached the required log files as a github attachment, and not as a pastebin/mclogs link.

**Comment by Shigure-Ruiseki** [comment]
Oh cause by I PR my api to GTNHLib by in this mod not clean up, I fix it now
