### ISSUE TITLE
[Issue]: NoClassDefFoundError: com/ibm/icu/impl/Pair on Java 25 crashes game on startup

### ISSUE THREAD

**Issue by erialsan** [Louis-LD29/OmoshiroiKamo#180]
### Description

Body:
Environment

omoshiroikamo: 1.5.1
Minecraft: 1.7.10
Forge: 10.13.4.1614
Java: 25.0.2 (Eclipse Temurin)
OS: OpenSUSE Linux (amd64)

Description
The game crashes during the INITIALIZATION phase with the following error:
java.lang.NoClassDefFoundError: com/ibm/icu/impl/Pair
    at ruiseki.omoshiroikamo.core.network.PacketHandler.getNewId(PacketHandler.java:218)
    at ruiseki.omoshiroikamo.core.network.PacketHandler.register(PacketHandler.java:76)
    ...
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.impl.Pair

This issue started after updating from 1.5.0.9 to 1.5.1. The previous version (1.5.0.9) did not have this problem.

### fml_client_latest.log, and crash reports, if any.

https://mclo.gs/Js6AHaF

### I have submitted the required files

- [x] I confirm that i have attached the required log files as a github attachment, and not as a pastebin/mclogs link.
